version: "3.5"

services:

  postgres:
    container_name: postgres
    image: postgres:13.2
    network_mode: bridge
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=customer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin
  # API Component*****************************************
  transactionService:
    image: transaction-service:latest
    network_mode: bridge
    container_name: transaction-service
    expose:
      - 8088
    ports:
      - 8088:8088
    environment:
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/customer
      - SPRING_LIQUIBASE_USERNAME=admin
      - SPRING_LIQUIBASE_PASSWORD=password
      - DB_HOST=postgres
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres_data:
  pgadmin_data: